export interface IUser {
    _id?: string,
    email: string,
    username: string,
    gender: string,
    languages: string[],
    dogBreed: string,
    userImage: string,
    dogImage?: string,
    birthday?: string,
    dogAge?: string,
    favoriteToy?: string,
    dogDescription?: string,
    availability: {
        dayTime: string,
        weekDay: string[],
    },
    description: string,
    location: {
        bottomLeft: number[],
        topRight: number[],
    },
    favorite: [],
    likes: string[],
    matches: string[],
}